### ISSUE TITLE
gnome-terminal only gives zeros in left most column

### ISSUE THREAD

**Issue by bob912** [wick3dr0se/matrix#4]
Hey, love this project. Works great in my slackware instance.

However under RHEL8, either non X11 CLI or in gnome-terminal, all I get is zeros cascading down the leftmost column in the terminal.

Are you able to test this or suggest how I could debug it?

Thanks.

**Comment by wick3dr0se** [comment]
Now that is a rather interesting issue.. I will see what I can figure out but off the top of my head that makes no sense. I have designed this to be completely random; It should not be possible the first column could generate 0's consistently at all. I will have to spin up a VM and check into this but if you find anything out, please do share!

**Comment by bob912** [comment]
I probably wasn't quite clear in my description above. I get only zeros in the left most column. I get nothing in the rest of the terminal - i.e. columns 2+ are totally empty.
I thought I'd entered something wrong on my work computer since I had to type it in manually, but I did a direct copy from your source here into a VM at home and get the same result.

**Comment by wick3dr0se** [comment]
Can you verify what version of Bash you are using? It seems to me it may not support checkwinsize or SRANDOM

Also which terminal emulator are you using?

**Comment by bob912** [comment]
SRANDOM
RHEL8 is on bash 4.4, SRANDOM not available until 5.1.
I replaced all instances of 'SRANDOM' with '$RANDOM' and it works perfectly - matrix all over my screen.
Thanks for the great tip on what it might be!

**Comment by wick3dr0se** [comment]
@bob912 Yea, currently I have it setup for 5.1 or later but I was suggested [this](https://www.reddit.com/r/bash/s/mny01UVsCF) change in a comment on Reddit. And because RANDOM isn't as random as SRANDOM, I'd preferrably reference that. Looks like `sed` syntax though and I've yet to look into it

**Comment by bob912** [comment]
Yeah, that's just some sed to do what I did. I'm not fussed - I'm happy to hack mine like that to get it to work on the older system.
